
# stage1 as builder
FROM registry.access.redhat.com/ubi8/nodejs-18:1-71.1695741533 as builder
# Copy the package.json and install dependencies
COPY package*.json ./
RUN npm install
# Copy rest of the files
COPY . .
# Build the project
RUN npm run build


FROM registry.access.redhat.com/ubi9/nginx-124 as production-build
COPY nginx.conf /etc/nginx/nginx.conf
## Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*
# Copy from the stage 1
COPY --from=builder /dist /usr/share/nginx/html/nested-app
EXPOSE 8080
ENTRYPOINT ["nginx", "-g", "daemon off;"]